{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bettafish.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-web" $fullName }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: bettafish-tls-secret
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ printf "%s-web" $fullName }}
            port:
              number: {{ .Values.bettafish.service.ports.api }}
{{- end -}}