{{- if and .Values.postgres.enabled .Values.postgres.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bettafish.fullname" . }}-postgres-auth
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
{{- end }}


