{{- if .Values.postgres.enabled }}
{{- $fullName := include "bettafish.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-postgres" $fullName }}
  labels:
    {{- include "bettafish.labels" . | nindent 4 }}
spec:
  serviceName: {{ printf "%s-postgres" $fullName }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bettafish.name" . }}
      app.kubernetes.io/component: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bettafish.name" . }}
        app.kubernetes.io/component: postgres
        {{- include "bettafish.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgres-auth" $fullName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgres-auth" $fullName }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgres-auth" $fullName }}
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ printf "%s-postgres" $fullName }}
      nodeSelector:
        kubernetes.io/hostname: k8sworker1
{{- end }}


